### ISSUE TITLE
Test run does not start with an error "java.lang.NoClassDefFoundError: Could not initialize class io.qase.cucumber5.guice.module.Cucumber5Module"

### ISSUE THREAD

**Issue by kisels** [qase-tms/qase-java#109]
Hi!
I faced with the issue while integrating Qase with Cucumber 5 + TestNg +  Java.

Issue: Test run did not started

Preconditions:

Java
TestNG
Cucumber 5
Maven

1. I followed the instructions described in the README.md: `<dependencies>
    <dependency>
        <groupId>io.qase</groupId>
        <artifactId>qase-cucumber5-jvm</artifactId>
        <version>3.0.4</version>
    </dependency>
</dependencies>`
2. Was added to @CucumberOptions plugin  io.qase.cucumber5.QaseEventListener 
3. Was used the following command for the execution ` mvn clean test -DQASE_ENABLE=true -DQASE_PROJECT_CODE=project-code -DQASE_RUN_NAME=NEW_RUN_NAME -DQASE_RUN_DESCRIPTION=NEW_RUN_DESCRIPTION -DQASE_API_TOKEN=api-token`

Tests didn't start to run with an issues `java.lang.AbstractMethodError: Missing implementation of resolved method abstract configure()V of abstract class com.google.inject.AbstractModule. java.lang.NoClassDefFoundError: Could not initialize class io.qase.cucumber5.guice.module.Cucumber5Module`

**Comment by savkk** [comment]
Hi @kisels !
what version of jdk are you using?

**Comment by kisels** [comment]
JDK 11.0 11

**Comment by savkk** [comment]
Could you write what dependencies are added to your project?
