### ISSUE TITLE
Annotation @CaseId is deperecated

### ISSUE THREAD

**Issue by tkrisztian95** [qase-tms/qase-java#132]
Im using the 
```
<dependency>
      <groupId>io.qase</groupId>
      <artifactId>qase-junit5</artifactId>
      <version>3.2.0</version>
    </dependency>
```
and I get the following deprecation message:
![image](https://github.com/qase-tms/qase-java/assets/8113120/06b66055-75d6-4e76-b269-13e115b8d6e7)

Please update the code examples provided in the project readme to the new/preferred annotations E.g `@QaseId` instead of `@CaseId`. 

Thanks!

**Comment by NickVolynkin** [comment]
@tkrisztian95 thanks!

**Comment by NickVolynkin** [comment]
Some occurrencies:
* https://github.com/qase-tms/qase-java/blob/master/qase-api/README.md?plain=1#L427
* all Cucumber examples, such as in https://github.com/qase-tms/qase-java/blob/master/qase-cucumber3-jvm/README.md#description
