### ISSUE TITLE
Error in running cucumber junit file

### ISSUE THREAD

**Issue by juliusortiz** [qase-tms/qase-java#135]
I have encountered this error upon executiong my Junit cucumber runner file:
java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null

Upon checking the QaseEventListener.java there is an error related to path

<img width="792" alt="Screenshot 2024-05-27 at 5 02 14 PM" src="https://github.com/qase-tms/qase-java/assets/48352384/f21ac4e9-8d24-4ab0-8a89-35483043b3eb">

**Comment by juliusortiz** [comment]
<img width="1770" alt="Screenshot 2024-05-27 at 5 19 59 PM" src="https://github.com/qase-tms/qase-java/assets/48352384/ac4ed45c-4bc5-46bc-80dd-dbfb195ca985">
<img width="1770" alt="Screenshot 2024-05-27 at 5 19 59 PM" src="https://github.com/qase-tms/qase-java/assets/48352384/ac4ed45c-4bc5-46bc-80dd-dbfb195ca985">

**Comment by juliusortiz** [comment]
Hello sir. @savkk has there any updates on this? I dont have an Idea with regards the gherkinParser.parse(path)

**Comment by savkk** [comment]
@juliusortiz Hello! I have fixed this issue in 3.2.1 version. Could you try it?

**Comment by juliusortiz** [comment]
Hello. Thank you for the quick fix. It’s already working on my end :)
