### ISSUE TITLE
While trying to send a NewTestCaseReport with steps that have attachments the API will not process the request

### ISSUE THREAD

**Issue by alex-mahu** [qase-tms/qase-java#15]
Based on the documentation https://developers.qase.io/#add-a-new-test-run-result when adding a NewTestCaseReport the type of the attachments for Step must be a List<String> while the code requests a List<Attachment> (https://github.com/qase-tms/qase-java/blob/master/qase-api/src/main/java/io/qase/api/models/v1/testrunresults/Step.java)

This causes the request to create the test case report to fail as the API can not process the request.

**Comment by savkk** [comment]
Problems with the contract fixed in 2.0.0
