### ISSUE TITLE
qase-junit4 - Failed cases marked as passed

### ISSUE THREAD

**Issue by mklanglois** [qase-tms/qase-java#22]
I'm using the qase-junit4 integration with Maven to run automated tests and upload the results to Qase. My failed test cases are being marked as passed. 

When I click into the result, it looks as though the case was run twice -- I see "Result 1" which failed correctly and automatically created a new defect, and "Result 2" which passed. However I ran each test case only once. The passing Result 2 seems to be overwriting the failed result and the case is marked as passed overall.

![image](https://user-images.githubusercontent.com/29211817/141831497-cb2fb7b1-b6fb-4ba0-8914-3c907223924f.png)

![image](https://user-images.githubusercontent.com/29211817/141831670-b3238dd7-b85f-4d43-9bcb-0b982e88cc21.png)

**Comment by savkk** [comment]
@mklanglois thank you. I'm going to fix it in version 2.0.0

**Comment by savkk** [comment]
@mklanglois v2.0.0 has published to maven central, try to use it

**Comment by mklanglois** [comment]
It's working! Thanks for your help.
