### ISSUE TITLE
Vulnerability warnings in qase-api dependendencies

### ISSUE THREAD

**Issue by sergeidyga** [qase-tms/qase-java#47]
Hello Qase people!

Idea warns about some vulnerable dependencies in `qase-api`
<img width="1020" alt="Screenshot 2022-04-20 at 12 13 16" src="https://user-images.githubusercontent.com/87765162/164194792-af0fe3c8-c434-434e-bde3-594880a87e01.png">

**Comment by savkk** [comment]
thanks! fixed
