### ISSUE TITLE
feat: support JUnit 4/5 screenshots

### ISSUE THREAD

**Issue by sharovatov** [qase-tms/qase-java#59]
currently our JUnit reporters aren't able to send attachments (even though API supports it -- see here https://github.com/qase-tms/qase-java/tree/master/qase-api)

JUnit can create screenshots and these screenshots should be sent to our API.

**Comment by savkk** [comment]
> JUnit can create screenshots and these screenshots should be sent to our API.

The responsibility for taking screenshots should be on the user, we should only provide an easy way to send the screenshot (or log, or another type of attachment) to the Qase.

I think the JS implementation of screenshots uploading through a folder is not very good. It would be better if we provide the user with a simple method that will add attachment to the current step.
