### ISSUE TITLE
Support passing headers for all reporters

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-java#73]
Example from PHPUnit reporter:
`X-Client: qaseapi=v1.0.0-alpha.3;qase-phpunit=v1.0.0-alpha.3;phpunit=9.5.13`
`X-Platform: os=Linux;arch=aarch64;php=8.1.3;composer=2.2.7`
Reference example:
`X-Client: qaseapi=[API_VERSION];qase-[REPORTER_NAME]=[REPORTER_VERSION];[FRAMEWORK_NAME]=[FRAMEWORK_VERSION]`
`X-Platform: os=[OS_NAME];arch=[ARCH];[LANG]=[LANG_VER]`

Example implementation:
https://github.com/qase-tms/qase-phpunit/blob/7ce4ff76c0030543885333909415c3c05a25e471/src/HeaderManager.php#L43

- cucumber3
- cucumber4
- cucumber5
- junit4
- junit5
- testng

**Comment by mbirintsev** [comment]
@1ivliev , 

Could you please take a look at the related PR #76? Does it implement the requirements?

Thank you

**Comment by 1ivliev** [comment]
@mbirintsev 
Hi! I'll be back with an answer a bit later

**Comment by 1ivliev** [comment]
@mbirintsev Hi! Can you tell me about dependencies, in my case they are not explicitly written in pom.xml?
<img width="911" alt="image" src="https://user-images.githubusercontent.com/64368690/190075208-784b70fc-9643-4ed9-9b1d-89d666f66e74.png">

**Comment by mbirintsev** [comment]
@1ivliev , good day

Seems `qase-testng` subproject uses a previous version of `qase-api`. Could you please make sure the right one is in the classpath? If I faced the issue I would `mvn clean` -> Removing local .m2 repo -> Invalidate caches and restart in IntelIJ IDEA -> `mvn compile`. 

PS: sometimes IDEA is confused with the dependencies version (in this case a version from https://mvnrepository.com/artifact/io.qase/qase-api could be in use)

**Comment by 1ivliev** [comment]
@mbirintsev Hi! Following your path.
I executed the next commands:
`mvn clean` -> Removing local .m2 repo -> Invalidate caches and restart in IntelIJ IDEA -> `mvn compile`
`mvn clean` -> Removing local .m2 repo -> Rebuild Project -> `mvn compile`
But I keep encountering an error:
[log.txt](https://github.com/qase-tms/qase-java/files/9584541/log.txt)
Can you tell me what's wrong?

**Comment by mbirintsev** [comment]
@1ivliev , hi!

Did you try solutions from https://stackoverflow.com/questions/20137020/why-does-intellij-give-me-package-doesnt-exist-error ?

**Comment by mbirintsev** [comment]
> Can you tell me what's wrong?

Well, according to the details above, this looks like IDEA bug. The package itself exists, does not it? 
As I could conclude from the SO question comments and discussion, the error could be triggered by different reasons. 

And as far as I understand, having more than one resource for some project (in our case it is `io.qase:qase-api:2.2.0`) is enough reason to cause the IDE to confuse. Truly, there are 2 versions of the package - **with** and **without** the package. So, the one **without** takes precedence.
